name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # or specify '3.8' or '3.9' if you want to match your local Python version exactly
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools wheel twine  # Install setuptools, wheel, and twine
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel  # Build source and wheel package
    - name: Publish package
      run: |
        twine upload dist/*  # Upload the package to PyPI using twine
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
